"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$custom\
$git_metrics\
$cmd_duration\
$line_break\
$python\
$character"""

[directory]
style = "blue"

[character]
success_symbol = "[❯](blue)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[custom.jj]
when = "jj-starship detect"
shell = ["jj-starship"]
format = "$output "

[git_metrics]
format = '(([▴$added]($added_style))([▿$deleted]($deleted_style)) )'
added_style = 'green'
deleted_style = 'red'
ignore_submodules = true
disabled = false
